### ISSUE TITLE
Is it  an official lsp4ij project?

### ISSUE THREAD

**Issue by angelozerr** [MicroShed/lsp4ij#6]
I noticed that you have created this project to have a language server support for intellij   which is a copy paste from intellij quarkus lsp4ij version which is very old.

With @fbricon we would like perhaps  to extract our lsp4ij in a new project which fixes so many bugs than your current version of lsp4ij and provide lsp console.

IMHO we should avoid having several repositories for lsp4ij. Is it a temporary repository for lsp4ij ? Or do you plan to maintain your own lsp4ij ?

**Comment by yeekangc** [comment]
We are looking at refactoring what we have and work toward a common component/project.  Hence, this project as a starting point.  We look forward to working with you all to evolve it and build a common lsp4ij.

**Comment by angelozerr** [comment]
Thanks @yeekangc for your answer.

We need to discuss with @fbricon about the repository because our idea was to host lsp4ij in https://github.com/redhat-developer. MicroShed is for microservices although LSP support for IJ can be used without microservices

**Comment by mrglavas** [comment]
@angelozerr @fbricon I've provided more context of what we've been up to in Gitter here: https://app.gitter.im/#/room/#eclipse_microprofile-languageserver:gitter.im. We've also been looking at refactoring LSP4MP and LSP4Jakarta. More details in what I've posted there for discussion.

**Comment by yeekangc** [comment]
MicroShed isn't for microservices alone.  Then, sharp eyes.  We should update the description.

Open to discuss further as @mrglavas noted.  Our intention is to collaborate with the community to build and evolve lsp4ij.

**Comment by mrglavas** [comment]
Liberty Tools for IntelliJ `24.0.9` adopted the official LSP4IJ plugin. I've updated the README to reflect the current status.
