### ISSUE TITLE
Default highlighting for diagnostics does not match VS Code

### ISSUE THREAD

**Issue by turkeylurkey** [MicroShed/lsp4ij#8]
When a language server does not set a severity on a diagnostic we default to INFO. On IntelliJ this means no highlighting on screen. 
<img width="469" alt="image" src="https://github.com/OpenLiberty/liberty-language-server/assets/24705144/1ff08582-ae3f-4b50-af18-905c906a9f0c">

It would be better to mimic VS Code which displays a red underline just to make sure the diagnostic is obvious. If the language server sets a certain severity we should honour that.

**Comment by mrglavas** [comment]
@turkeylurkey Did you intend to keep this issue open? I see there's a PR attached that got merged. Was this contributed back to https://github.com/redhat-developer/lsp4ij?

**Comment by turkeylurkey** [comment]
Github failed to close it. The code was contributed to lsp4ij.
